### PR TITLE
basic IPP protocol handler

### PR DESCRIPTION
**Pull request by RishabhArya**

### CODE REVIEW

**Comment by alexpevzner** [comment]
Please, put *your* name as the copyright holder of the airscan-ipp.c file

**Comment by RishabhArya** [comment]
> Please, put _your_ name as the copyright holder of the airscan-ipp.c file

Alright sir, Thank you

**Comment by alexpevzner** [comment]
Hi @RishabhArya,

I've fixed build and added minimalist support for ID_PROTO_IPP, so now it should be configurable via `/etc/sane.d/airscan.conf`:

    [devices]
    IPP device = http://1.2.3.4:5678/ipp/scan, ipp

Please, before committing, verify that your code builds, and use relevant comments to your commits -- eventually your commuts will be merged into the main `sane-airscan` tree.

The next steps for you:
1. Using any HTTP library of your choice, update your `ipp_GetPrinterAttributes` example, so it will send request to the printer and receive response. libcups contains HTTP client, that you can use, or you can use libcurl, it's up to you
2. Implement dumping of IPP responses, returned by printer, in a textual form
3. Make sure that printer really accepts your request and returns Printer Attributes, not the error message

After this work will be done, next steps will be moving this code into the `sane-airscan-ipp`

**Comment by RishabhArya** [comment]
Thank You Sir,
Will insure each point next time i commit.

**Pull request merged**
